#!/usr/bin/env python3
"""
generate_embedded_assets.py

Compile-time tooling for ZoneClient that bundles client gamedata assets
into C++ source code as byte arrays to avoid MSVC string literal length limits
and enable self-contained DLL provisioning.
"""

import argparse
import os
import sys

MOD_FILES = [
    "configs/mod_system_zone_online.ltx",
    "configs/ui/zone_ui_server_list.xml",
    "configs/text/eng/ui_zone.xml",
    "configs/text/rus/ui_zone.xml",
    "scripts/modxml_zone_main_menu.script",
    "scripts/zone_menu_patch.script",
    "scripts/zone_net.script",
    "scripts/zone_main.script",
    "scripts/zone_ui_server_list.script",
    "scripts/zone_ai_proxy.script",
    "scripts/zone_dummy.script",
    "scripts/zone_hud.script",
    "scripts/zone_safezone.script",
    "scripts/zone_worldevent.script",
]

CLEAN_SERVER_LIST_XML_REL = "configs/ui/zone_ui_server_list.xml"


def format_byte_array(var_name: str, data: bytes, comment: str) -> str:
    lines = [
        f"    // {comment} ({len(data)} bytes)",
        f"    static const unsigned char {var_name}[] = {{",
    ]
    chunk_size = 16
    for i in range(0, len(data), chunk_size):
        chunk = data[i:i + chunk_size]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"        {hex_str},")
    lines.append("        0x00")
    lines.append("    };")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate compile-time embedded assets from gamedata for ZoneClient"
    )
    parser.add_argument("--gamedata", required=True, help="Path to gamedata directory")
    parser.add_argument("--out-h", required=True, help="Path to output C++ header file")
    parser.add_argument("--out-cpp", required=True, help="Path to output C++ source file")

    args = parser.parse_args()

    gamedata_dir = os.path.abspath(args.gamedata)
    if not os.path.isdir(gamedata_dir):
        print(f"Error: Gamedata directory does not exist: {gamedata_dir}", file=sys.stderr)
        sys.exit(1)

    assets_data = []
    clean_server_list_idx = -1

    for idx, rel_path in enumerate(MOD_FILES):
        full_path = os.path.join(gamedata_dir, rel_path)
        if not os.path.isfile(full_path):
            print(f"Error: Required asset file missing: {full_path}", file=sys.stderr)
            sys.exit(1)

        with open(full_path, "rb") as f:
            data = f.read()

        assets_data.append((idx, rel_path, data))

        if rel_path.replace("\\", "/") == CLEAN_SERVER_LIST_XML_REL:
            clean_server_list_idx = idx

    if clean_server_list_idx < 0:
        print(
            f"Error: Clean server list XML ({CLEAN_SERVER_LIST_XML_REL}) not found in asset list",
            file=sys.stderr,
        )
        sys.exit(1)

    # 1. Generate Header (.h)
    header_content = """#pragma once
#include <cstddef>

namespace AssetProvisioner
{
    struct EmbeddedAsset
    {
        const wchar_t* relativePath;
        const char* data;
        size_t size;
    };

    extern const EmbeddedAsset g_EmbeddedAssets[];
    extern const size_t g_EmbeddedAssetsCount;

    extern const char* g_CleanServerListXml;
    extern const size_t g_CleanServerListXmlSize;
}
"""

    out_h_path = os.path.abspath(args.out_h)
    out_cpp_path = os.path.abspath(args.out_cpp)

    os.makedirs(os.path.dirname(out_h_path), exist_ok=True)
    os.makedirs(os.path.dirname(out_cpp_path), exist_ok=True)

    with open(out_h_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header_content)

    # 2. Generate Source (.cpp)
    header_filename = os.path.basename(out_h_path)
    cpp_lines = [
        "// Generated by generate_embedded_assets.py - DO NOT EDIT DIRECTLY",
        "",
        f'#include "{header_filename}"',
        "",
        "namespace AssetProvisioner",
        "{",
    ]

    # Generate byte arrays
    for idx, rel_path, data in assets_data:
        var_name = f"ASSET_DATA_{idx}"
        cpp_lines.append(format_byte_array(var_name, data, rel_path))
        cpp_lines.append("")

    # Generate g_EmbeddedAssets array
    cpp_lines.append("    extern const EmbeddedAsset g_EmbeddedAssets[] = {")
    for idx, rel_path, _ in assets_data:
        # Construct Windows relative path starting with gamedata\\
        # e.g. L"gamedata\\configs\\ui\\zone_ui_server_list.xml"
        norm_rel = rel_path.replace("/", "\\\\")
        wpath = f'L"gamedata\\\\{norm_rel}"'
        var_name = f"ASSET_DATA_{idx}"
        cpp_lines.append(
            f"        {{ {wpath}, (const char*){var_name}, sizeof({var_name}) - 1 }},"
        )
    cpp_lines.append("    };")
    cpp_lines.append("")

    # Generate count
    cpp_lines.append(
        "    extern const size_t g_EmbeddedAssetsCount = sizeof(g_EmbeddedAssets) / sizeof(g_EmbeddedAssets[0]);"
    )
    cpp_lines.append("")

    # Generate g_CleanServerListXml and size
    clean_var = f"ASSET_DATA_{clean_server_list_idx}"
    cpp_lines.append(f"    extern const char* g_CleanServerListXml = (const char*){clean_var};")
    cpp_lines.append(
        f"    extern const size_t g_CleanServerListXmlSize = sizeof({clean_var}) - 1;"
    )
    cpp_lines.append("}")
    cpp_lines.append("")

    with open(out_cpp_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(cpp_lines))

    print(
        f"Successfully generated embedded assets ({len(assets_data)} files):"
    )
    print(f"  Header: {out_h_path}")
    print(f"  Source: {out_cpp_path}")


if __name__ == "__main__":
    main()
