package ai

import (
	"sync"
	"testing"
	"time"
)

// TestSpawnSquad_AStarPath verifies that SpawnSquad properly creates a squad,
// registers it in the manager, and calculates a valid A* patrol route.
func TestSpawnSquad_AStarPath(t *testing.T) {
	sm := NewSquadManager()

	if sm.Count() != 0 {
		t.Fatalf("expected count 0 for new manager, got %d", sm.Count())
	}
	if squads := sm.GetAllSquads(); len(squads) != 0 {
		t.Fatalf("expected 0 squads from GetAllSquads, got %d", len(squads))
	}

	sq1 := sm.SpawnSquad("l01_escape", 10.0, 5.0, 20.0, "loner")
	if sq1 == nil {
		t.Fatal("expected non-nil squad from SpawnSquad")
	}

	if sq1.ID != 1 {
		t.Errorf("expected squad ID 1, got %d", sq1.ID)
	}
	if sq1.Level != "l01_escape" {
		t.Errorf("expected level 'l01_escape', got '%s'", sq1.Level)
	}
	if sq1.Position != [3]float32{10.0, 5.0, 20.0} {
		t.Errorf("expected position [10, 5, 20], got %v", sq1.Position)
	}
	if sq1.Faction != "loner" {
		t.Errorf("expected faction 'loner', got '%s'", sq1.Faction)
	}
	if sq1.State != AIStatePatrol {
		t.Errorf("expected state AIStatePatrol, got %v", sq1.State)
	}
	if sq1.Health != 100.0 {
		t.Errorf("expected health 100.0, got %f", sq1.Health)
	}
	if sm.Count() != 1 {
		t.Errorf("expected squad count 1, got %d", sm.Count())
	}

	// Verify A* path generation
	if len(sq1.Path) == 0 {
		t.Fatal("expected non-empty path generated by A*")
	}

	startWP := sq1.Path[0]
	if startWP != (Waypoint{X: 10.0, Y: 5.0, Z: 20.0}) {
		t.Errorf("expected path start waypoint {10, 5, 20}, got %v", startWP)
	}

	expectedGoal := Waypoint{X: 10.0 + patrolRadius, Y: 5.0, Z: 20.0 + patrolRadius}
	goalWP := sq1.Path[len(sq1.Path)-1]
	if goalWP != expectedGoal {
		t.Errorf("expected path goal waypoint %v, got %v", expectedGoal, goalWP)
	}

	// Verify path continuity: consecutive waypoints should be within coarse grid step
	const maxStepDist = 8.01
	for i := 1; i < len(sq1.Path); i++ {
		dist := heuristic(sq1.Path[i-1], sq1.Path[i])
		if dist > maxStepDist {
			t.Errorf("gap between waypoint %d and %d is %f, exceeds expected step %f", i-1, i, dist, maxStepDist)
		}
	}

	// Verify retrieval through GetSquad
	retrieved, ok := sm.GetSquad(sq1.ID)
	if !ok || retrieved != sq1 {
		t.Fatalf("failed to retrieve squad 1 through GetSquad: ok=%v, squad=%v", ok, retrieved)
	}

	// Verify non-existent ID
	if _, ok := sm.GetSquad(9999); ok {
		t.Error("expected ok=false when querying non-existent squad ID")
	}

	// Spawn a second squad and verify ID incrementation
	sq2 := sm.SpawnSquad("l05_bar_rostok", 50.0, 0.0, 50.0, "duty")
	if sq2.ID != 2 {
		t.Errorf("expected squad ID 2, got %d", sq2.ID)
	}
	if sm.Count() != 2 {
		t.Errorf("expected count 2, got %d", sm.Count())
	}
	if all := sm.GetAllSquads(); len(all) != 2 {
		t.Errorf("expected 2 squads from GetAllSquads, got %d", len(all))
	}
}

// TestTick_MovementProgression tests that Tick moves a squad forward along its waypoints.
func TestTick_MovementProgression(t *testing.T) {
	sm := NewSquadManager()
	sq := sm.SpawnSquad("l01_escape", 0.0, 0.0, 0.0, "clear_sky")

	initialPos := sq.Position
	if initialPos != [3]float32{0, 0, 0} {
		t.Fatalf("unexpected initial position %v", initialPos)
	}

	// First tick: Squad is at waypoint 0 (0,0,0), advances target to waypoint 1 (8,0,0),
	// and moves patrolStepSize (2.0) units toward it along the X-axis.
	sm.Tick(time.Now(), nil)
	if sq.Position[0] != 2.0 || sq.Position[1] != 0.0 || sq.Position[2] != 0.0 {
		t.Errorf("expected position [2, 0, 0] after tick 1, got %v", sq.Position)
	}

	// Second tick: moves another 2.0 units
	sm.Tick(time.Now(), nil)
	if sq.Position[0] != 4.0 || sq.Position[1] != 0.0 || sq.Position[2] != 0.0 {
		t.Errorf("expected position [4, 0, 0] after tick 2, got %v", sq.Position)
	}

	// Third tick: moves another 2.0 units
	sm.Tick(time.Now(), nil)
	if sq.Position[0] != 6.0 || sq.Position[1] != 0.0 || sq.Position[2] != 0.0 {
		t.Errorf("expected position [6, 0, 0] after tick 3, got %v", sq.Position)
	}

	// Fourth tick: dist to waypoint 1 (8,0,0) is 2.0 <= patrolStepSize,
	// snaps to waypoint 1 and advances PathIndex to 2.
	sm.Tick(time.Now(), nil)
	if sq.Position[0] != 8.0 || sq.Position[1] != 0.0 || sq.Position[2] != 0.0 {
		t.Errorf("expected position [8, 0, 0] after tick 4, got %v", sq.Position)
	}
	if sq.PathIndex != 2 {
		t.Errorf("expected PathIndex 2 after reaching waypoint 1, got %d", sq.PathIndex)
	}

	// Fifth tick: continues moving towards waypoint 2 (16,0,0)
	sm.Tick(time.Now(), nil)
	if sq.Position[0] != 10.0 {
		t.Errorf("expected position X=10 after tick 5, got %v", sq.Position)
	}
}

// TestTick_WaypointLooping tests that a squad automatically loops back to the start
// of its waypoint list upon reaching the circuit end.
func TestTick_WaypointLooping(t *testing.T) {
	sm := NewSquadManager()
	sq := sm.SpawnSquad("l02_garbage", 0.0, 0.0, 0.0, "bandit")

	// Set a simple 3-waypoint triangle circuit
	w0 := Waypoint{X: 0, Y: 0, Z: 0}
	w1 := Waypoint{X: 4, Y: 0, Z: 0}
	w2 := Waypoint{X: 4, Y: 0, Z: 4}

	sq.Path = []Waypoint{w0, w1, w2}
	sq.Position = [3]float32{0, 0, 0}
	sq.PathIndex = 0

	// Tick 1: at w0, advances target to w1, moves 2.0 -> (2, 0, 0)
	sm.Tick(time.Now(), nil)
	if sq.Position != [3]float32{2, 0, 0} {
		t.Fatalf("expected position [2, 0, 0], got %v", sq.Position)
	}

	// Tick 2: dist to w1 is 2.0 <= 2.0 -> snaps to w1 (4, 0, 0), advances target to w2 (index 2)
	sm.Tick(time.Now(), nil)
	if sq.Position != [3]float32{4, 0, 0} {
		t.Fatalf("expected position [4, 0, 0], got %v", sq.Position)
	}
	if sq.PathIndex != 2 {
		t.Fatalf("expected PathIndex 2, got %d", sq.PathIndex)
	}

	// Tick 3: moves toward w2 along Z by 2.0 -> (4, 0, 2)
	sm.Tick(time.Now(), nil)
	if sq.Position != [3]float32{4, 0, 2} {
		t.Fatalf("expected position [4, 0, 2], got %v", sq.Position)
	}

	// Tick 4: dist to w2 is 2.0 <= 2.0 -> snaps to w2 (4, 0, 4), and LOOPS PathIndex to 0!
	sm.Tick(time.Now(), nil)
	if sq.Position != [3]float32{4, 0, 4} {
		t.Fatalf("expected position [4, 0, 4], got %v", sq.Position)
	}
	if sq.PathIndex != 0 {
		t.Fatalf("expected PathIndex to loop back to 0, got %d", sq.PathIndex)
	}

	// Tick 5: target is now w0 (0, 0, 0), moves toward w0
	sm.Tick(time.Now(), nil)
	if sq.Position[0] >= 4.0 || sq.Position[2] >= 4.0 {
		t.Fatalf("expected squad to move toward w0 (0,0,0), position is %v", sq.Position)
	}
}

// TestDespawnAndDeadSquadFiltering tests despawning squads and ensuring dead squads
// are skipped during Tick updates and broadcasts.
func TestDespawnAndDeadSquadFiltering(t *testing.T) {
	sm := NewSquadManager()

	s1 := sm.SpawnSquad("l01_escape", 10, 0, 10, "loner")
	s2 := sm.SpawnSquad("l01_escape", 20, 0, 20, "bandit")
	s3 := sm.SpawnSquad("l01_escape", 30, 0, 30, "military")

	if sm.Count() != 3 {
		t.Fatalf("expected count 3, got %d", sm.Count())
	}

	// Mark squad 2 as Dead
	sm.SetSquadState(s2.ID, AIStateDead)
	if s2.State != AIStateDead {
		t.Fatalf("expected squad 2 state to be AIStateDead, got %v", s2.State)
	}

	s2PosBefore := s2.Position

	// Tick and record which squads are broadcast
	broadcastIDs := make(map[uint32]bool)
	sm.Tick(time.Now(), func(squadID uint32, state AIState, pos [3]float32) {
		broadcastIDs[squadID] = true
	})

	if !broadcastIDs[s1.ID] {
		t.Error("expected squad 1 to be broadcast")
	}
	if !broadcastIDs[s3.ID] {
		t.Error("expected squad 3 to be broadcast")
	}
	if broadcastIDs[s2.ID] {
		t.Error("expected dead squad 2 to be skipped from broadcast")
	}

	// Verify dead squad did not move
	if s2.Position != s2PosBefore {
		t.Errorf("dead squad moved from %v to %v", s2PosBefore, s2.Position)
	}

	// Despawn squad 1
	sm.DespawnSquad(s1.ID)
	if sm.Count() != 2 {
		t.Errorf("expected count 2 after despawning s1, got %d", sm.Count())
	}
	if _, ok := sm.GetSquad(s1.ID); ok {
		t.Error("expected squad 1 to not be found after despawn")
	}

	// Despawn non-existent ID should be a safe no-op
	sm.DespawnSquad(8888)
	if sm.Count() != 2 {
		t.Errorf("expected count 2 after despawning non-existent ID, got %d", sm.Count())
	}

	// Tick again: only s3 should broadcast
	broadcastIDs = make(map[uint32]bool)
	sm.Tick(time.Now(), func(squadID uint32, state AIState, pos [3]float32) {
		broadcastIDs[squadID] = true
	})

	if len(broadcastIDs) != 1 || !broadcastIDs[s3.ID] {
		t.Errorf("expected only squad 3 to broadcast, got %v", broadcastIDs)
	}

	// Despawn all remaining
	sm.DespawnSquad(s2.ID)
	sm.DespawnSquad(s3.ID)
	if sm.Count() != 0 {
		t.Errorf("expected count 0 after despawning all squads, got %d", sm.Count())
	}

	// Tick on empty manager should be safe and execute cleanly
	sm.Tick(time.Now(), func(squadID uint32, state AIState, pos [3]float32) {
		t.Errorf("unexpected broadcast on empty manager for squad %d", squadID)
	})
}

// TestBroadcastFn_Payload verifies that broadcastFn receives the exact squad ID,
// current state, and updated position.
func TestBroadcastFn_Payload(t *testing.T) {
	sm := NewSquadManager()

	s1 := sm.SpawnSquad("l01_escape", 100.0, 5.0, 100.0, "loner")
	s2 := sm.SpawnSquad("l01_escape", 200.0, 10.0, 200.0, "monolith")
	s3 := sm.SpawnSquad("l01_escape", 300.0, 15.0, 300.0, "ecolog")

	sm.SetSquadState(s2.ID, AIStateAttack)
	sm.SetSquadState(s3.ID, AIStateFlee)

	type broadcastRecord struct {
		id    uint32
		state AIState
		pos   [3]float32
	}

	received := make(map[uint32]broadcastRecord)
	sm.Tick(time.Now(), func(id uint32, state AIState, pos [3]float32) {
		received[id] = broadcastRecord{
			id:    id,
			state: state,
			pos:   pos,
		}
	})

	if len(received) != 3 {
		t.Fatalf("expected 3 broadcasts, received %d", len(received))
	}

	// Squad 1 (Patrol): position advanced by 2.0 units along X
	r1, ok1 := received[s1.ID]
	if !ok1 {
		t.Fatal("missing broadcast for squad 1")
	}
	if r1.state != AIStatePatrol {
		t.Errorf("expected squad 1 state AIStatePatrol, got %v", r1.state)
	}
	if r1.pos != s1.Position {
		t.Errorf("expected broadcast pos to match squad 1 pos %v, got %v", s1.Position, r1.pos)
	}

	// Squad 2 (Attack): non-patrol states do not advance patrol
	r2, ok2 := received[s2.ID]
	if !ok2 {
		t.Fatal("missing broadcast for squad 2")
	}
	if r2.state != AIStateAttack {
		t.Errorf("expected squad 2 state AIStateAttack, got %v", r2.state)
	}
	if r2.pos != [3]float32{200.0, 10.0, 200.0} {
		t.Errorf("expected squad 2 position [200, 10, 200], got %v", r2.pos)
	}

	// Squad 3 (Flee)
	r3, ok3 := received[s3.ID]
	if !ok3 {
		t.Fatal("missing broadcast for squad 3")
	}
	if r3.state != AIStateFlee {
		t.Errorf("expected squad 3 state AIStateFlee, got %v", r3.state)
	}
	if r3.pos != [3]float32{300.0, 15.0, 300.0} {
		t.Errorf("expected squad 3 position [300, 15, 300], got %v", r3.pos)
	}

	// Verify AIState string representations
	if AIStateIdle.String() != "Idle" {
		t.Errorf("unexpected string for AIStateIdle: %s", AIStateIdle.String())
	}
	if AIStatePatrol.String() != "Patrol" {
		t.Errorf("unexpected string for AIStatePatrol: %s", AIStatePatrol.String())
	}
	if AIStateAttack.String() != "Attack" {
		t.Errorf("unexpected string for AIStateAttack: %s", AIStateAttack.String())
	}
	if AIStateFlee.String() != "Flee" {
		t.Errorf("unexpected string for AIStateFlee: %s", AIStateFlee.String())
	}
	if AIStateDead.String() != "Dead" {
		t.Errorf("unexpected string for AIStateDead: %s", AIStateDead.String())
	}
	if AIState(99).String() != "Unknown" {
		t.Errorf("unexpected string for invalid AIState: %s", AIState(99).String())
	}
}

// TestGetAllSquadsAndSetSquadState verifies squad list retrieval and state modifications.
func TestGetAllSquadsAndSetSquadState(t *testing.T) {
	sm := NewSquadManager()

	s1 := sm.SpawnSquad("l01_escape", 0, 0, 0, "loner")
	s2 := sm.SpawnSquad("l02_garbage", 10, 0, 10, "bandit")

	squads := sm.GetAllSquads()
	if len(squads) != 2 {
		t.Fatalf("expected 2 squads, got %d", len(squads))
	}

	sm.SetSquadState(s1.ID, AIStateIdle)
	if s1.State != AIStateIdle {
		t.Errorf("expected squad 1 state AIStateIdle, got %v", s1.State)
	}

	sm.SetSquadState(s2.ID, AIStateAttack)
	if s2.State != AIStateAttack {
		t.Errorf("expected squad 2 state AIStateAttack, got %v", s2.State)
	}

	// Setting state on non-existent squad ID should be a safe no-op
	sm.SetSquadState(9999, AIStateDead)
	if sm.Count() != 2 {
		t.Errorf("expected count to remain 2, got %d", sm.Count())
	}
}

// TestConcurrentAccess_Race verifies thread safety of SquadManager under concurrent access
// using go test -race.
func TestConcurrentAccess_Race(t *testing.T) {
	sm := NewSquadManager()

	const numWorkers = 16
	const iterations = 100

	var wg sync.WaitGroup
	wg.Add(numWorkers)

	for w := 0; w < numWorkers; w++ {
		workerID := w
		go func() {
			defer wg.Done()
			for i := 0; i < iterations; i++ {
				switch (workerID + i) % 6 {
				case 0:
					// Spawn squad
					sm.SpawnSquad("l01_escape", float32(i*10), 0, float32(i*10), "stalker")
				case 1:
					// Read all squads and count
					_ = sm.Count()
					all := sm.GetAllSquads()
					if len(all) > 0 {
						_, _ = sm.GetSquad(all[0].ID)
					}
				case 2:
					// Modify state
					all := sm.GetAllSquads()
					if len(all) > 0 {
						target := all[i%len(all)]
						states := []AIState{AIStateIdle, AIStatePatrol, AIStateAttack, AIStateFlee, AIStateDead}
						sm.SetSquadState(target.ID, states[i%len(states)])
					}
				case 3:
					// Tick with broadcast reading data
					sm.Tick(time.Now(), func(squadID uint32, state AIState, pos [3]float32) {
						// Inside broadcast, safe to query the manager without deadlocking
						_, _ = sm.GetSquad(squadID)
					})
				case 4:
					// Despawn squads
					all := sm.GetAllSquads()
					if len(all) > 5 {
						sm.DespawnSquad(all[0].ID)
					}
				case 5:
					// Get non-existent
					_, _ = sm.GetSquad(uint32(99999 + i))
				}
			}
		}()
	}

	wg.Wait()
}
